function division(nb1, nb2) {
    return new Promise((resolve, reject) =>{
        // Si le nombre 2 vaut 0, on va rejeter la promesse : on ne peut la tenir
        if(nb2 === 0) {
            // reject prend en param√®tre la raison du rejet de la promesse
            // Il peut √™tre de n'importe quel type, souvent ce sera un obj Error
            reject(new Error("Division par 0 impossible"))
        }
        else {
            //Sinon, on peut tenir la promesse, donc on la r√©sout
            //Resolve, prend en param√®tre la valeur a renvoyer (n'importe quel type)
            resolve(nb1/nb2);
        }
    })
}

division(12,0)
    //then => sera d√©clench√© si la promesse est tenue
    .then((res) => {
        //res contient la r√©solution de la promesse, donc dans notre cas, le r√©sultat de la division
        console.log(`La division vaut ${res}`);
    })
    //catch => sera d√©clench√© si la promesse n'a pu √™tre tenue
    .catch((error) => {
        //error contient la raisin de pourquoi la promesse n'a pu √™tre tenue
        console.error(error.message);
    })
    //finally => sera d√©clench√© quoiqu'il arrive, qu'elle soit tenue ou non
    .finally(() => {
        console.log("Division faite, merci au revoir"); 
    });


// ___________________________
// Les promesses appliqu√©es √† notre omelette :
function preparer() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            let rand = Math.floor(Math.random() * 3);
            if(rand === 1) {
                reject(new Error("Oh non, les oeufs sont pourris ü§Æ"))               
            }
            else {
                resolve("Les oeufs sont battus ü•ö !")                
            }
        }, 3000)
    })
}

function cuire() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            let rand = Math.floor(Math.random() * 3);
            if(rand === 1) {
                reject(new Error("Oh non, l'omelette a br√ªl√© üî•"));
                
            }
            else {
                resolve("L'omelette est cuite, √ßa sent bon üç≥!");
            }
        }, 2000)
    })
    
}

function servir() {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            let rand = Math.floor(Math.random() * 3);
            if(rand === 1) {
                reject(new Error("Oh non, le serveur a gliss√© üßº"));
                
            }
            else {
                resolve("Voici votre omelette, bon app√©tit ! üçΩ");
            }
        }, 1000)
    })
}

// Version avec les then, catch, finally
// preparer()
//     .then((res) => {
//         console.log(res);
//         cuire()
//             .then((res2) => {
//                 console.log(res2);
//                 servir()
//                     .then((res3) => {
//                         console.log(res3);
                        
//                     })
//                     .catch((error) => {
//                         console.log(error.message);
                        
//                     })            
//             })
//             .catch((error) => {
//                 console.log(error.message);
//             })
//     })
//     .catch((error) => {
//         console.log(error.message);     
//     })

// Une fa√ßon plus simple de g√©rer les promesses : async await
async function omelette() {
    try {
        //On lance la promesse :
        //si tenue, j'ai le resultat dans res1
        //si non tenue, on va directement au bloc catch
        let res1 = await preparer();
        console.log(res1);
        let res2 = await cuire();
        console.log(res2);
        let res3 = await servir();
        console.log(res3);
    }
    catch(error){
        console.log(error.message);
        
    }
    //finally
}

omelette();